# This is a basic workflow to help you get started with Actions

name: Creating a docker image and running a container using github actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository check out into the runner
        uses: actions/checkout@v2

      - name: Description
        run: echo This code creates a docker image and runs a docker container out of it

      - name: Docker image creation
        run: docker build -t mageshprabha/dockerrepo .
        
      - name: Docker hub login
        run: echo "Logging into docker hub" | sudo docker login -u ${{secret.DockerUsername}} --password ${{secret.DockerPassword}}
        
      - name: Push image
        run: echo "pushing image into docker hub" | sudo docker push mageshprabha/dockerrepo
        
      - name: Run container
        run: docker run -i --name=con mageshprabha/dockerrepo /bin/bash
          
      - name: List of files
        run: ls
        
      - name: Working inside container
        run: docker-compose exec -T con
