# This is a basic workflow to help you get started with Actions

name: Creating a docker image and running a container using github actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Repository check out into the runner
        uses: actions/checkout@v2

      - name: Description
        run: echo This code creates a docker image and runs a docker container out of it

      - name: Docker image creation
        run: docker build -t mageshprabha/dockerrepo .
        
      - name: Docker hub login
        run: echo "Logging into docker hub" | sudo docker login -u ${{secrets.DOCKERUSERNAME}} --password ${{secrets.DOCKERPASSWORD}}
        
      - name: Push image
        run: echo "pushing image into docker hub" | sudo docker push mageshprabha/dockerrepo
        
      - name: Run container
        run: |
          docker run -i --name=con mageshprabha/dockerrepo /bin/bash
          docker start con
          
      - name: List of files
        run: ls
        
      - name: Python
        run: python Python/pythoncode.py
        
      - name: Docker images list
        run: docker images mageshprabha/dockerrepo
        
      - name: Docker container list
        run: docker ps
        
      - name: Working inside container
        run: |
          docker exec -i con /bin/bash -c "pwd
          ls
          java -version
          python"
